name: Java CI with Gradle

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: build sc2repo
      run: cd sc2repo && gradle clean build

    - name: build sc2tap
      run: cd sc2tap && gradle clean build

    - name: build sc2links
      run: cd sc2links && gradle clean build

    - name: build sc2meta
      run: cd sc2meta && gradle clean build

    - name: build sc2soda
      run: cd sc2soda && gradle clean build
  
